### PR TITLE
fix package exports

### PR DESCRIPTION
**Pull request by kylebarron**

### CODE REVIEW

**Comment by llimllib** [comment]
Confirmed that with a build made with this patch, this code works on node 20.11.1:

```
import * as Arrow from "apache-arrow";
import * as Parquet from "parquet-wasm";

const table = Arrow.tableFromArrays({ test: [42] });
process.stdout.write(
  Parquet.writeParquet(
    Parquet.Table.fromIPCStream(Arrow.tableToIPC(table, "stream")),
  ),
);```

**Comment by kylebarron** [comment]
Thanks! I just need to update this PR now that we don't have arrow2 and then I can merge

**Comment by kylebarron** [comment]
For some reason the types still aren't loading in some environments, but this is still progress.

**Comment by andresgutgon** [comment]
Hi, I'm trying this package in a nodejs script. I have a question. `initWasm` doesn't look necessary if we use nodejs. Is that correct?

**Comment by kylebarron** [comment]
As long as you use the Node entry point, that is correct. But if you're using the `/esm` entry point from Node, you still need to call `initWasm`

**Pull request merged**
