### PR TITLE
CI production build size summary

### PR DESCRIPTION
**Pull request by H-Plus-Time**
I would have liked to do a head vs target % change (apparently there's a way involving artifacts), but this is a sufficiently useful gauge. Presumably the artifacts required for that would also be used in package publishing.

As far as I can tell, it's only the JS bindings that differ between targets, so we can probably just do `pkg/esm/*.wasm` and be done with it.

### CODE REVIEW

**Review by kylebarron — APPROVED** [review]
lgtm. Where does the output go? I haven't used `GITHUB_STEP_SUMMARY` before

**Comment by H-Plus-Time** [comment]
Top level of the workflow for the PR/commit (disappointingly, 3 clicks from a PR (show all checks, pick anything, hit summary top left)). There's probably/hopefully a Github app that surfaces it in the PR (like Dependabot) :-/.

Also, pv apparently uses base-2 SI prefixes (about 5% deviation at the MiB vs MB level) 😞

**Comment by H-Plus-Time** [comment]
Excellent, found one, adding it now.

**Comment by kylebarron** [comment]
are the failing runs expected?

**Comment by H-Plus-Time** [comment]
:thinking: yeah, though it looks like we'd have to use a synthetic full target (the one in cargo.toml breaks with symbol collisions, presumably arrow1, arrow2 in the same bundle).

I ended up just switching away from scripts/build.sh (one platform target, multiple feature flags is relevant for reporting, while multiple targets, fixed feature flags is relevant for publishing). Since it's a new script, I figured I'd just ignore the arrow2 build as well (trivial to add it anyway, if we still want to keep an eye on build size for the duration of the deprecation window).

> A delta with the previous known size would also be cool, but that sounds pretty hard, and it's not too hard to find the most recent PR.

It looks like the deltas are fully functional (and correct) too :tada: .

Also, apparently, closing and re-opening PRs (so long as they still have un-merged changes) is sufficient to trigger fresh workflows (with the results based on the target branch), so that's all we have to do with the motivating example (#400 ) to see this in action.

**Comment by H-Plus-Time** [comment]
The comment output from the equivalent PR in my fork:

<h1>Asset Sizes</h1>
<table><tr><th>Asset</th><th>Uncompressed Size</th><th>Compressed Size</th></tr><tr><td>async_full/arrow1_bg.wasm</td><td>5.21MB $\color{red}\text{+174KB +3\%}$</td><td>1.22MB $\color{red}\text{+62.3KB +5\%}$</td></tr><tr><td>slim/arrow1_bg.wasm</td><td>4.6MB $\color{red}\text{+12.2KB +0\%}$</td><td>1.04MB $\color{green}\text{-2.12KB -0\%}$</td></tr><tr><td>sync/arrow1_bg.wasm</td><td>4.6MB $\color{red}\text{+12.2KB +0\%}$</td><td>1.04MB $\color{green}\text{-2.12KB -0\%}$</td></tr></table>

**Comment by kylebarron** [comment]
arrow2 hasn't gotten a commit in a month and at this point I consider it on its way to dying, sadly. So I'm content with deprecating and removing arrow2 as soon as the arrow1 bindings have a superset of functionality

**Comment by kylebarron** [comment]
Thanks again!

**Comment by kylebarron** [comment]
Hmm looks like this failed on my PR . https://github.com/kylebarron/parquet-wasm/actions/runs/7215812740/job/19660787302
image

Maybe that's because there wasn't a previous summary to download from?

**Pull request merged**
